Repository chihacknight/decarbonize-my-state, pull requests merged in 2022-04, with the labels that each got.

#44 Vehicles data
  data/Makefile
  data/final/buildings/buildings.json
  data/final/emissions/emissions.json
  data/final/vehicles/vehicles.json
  data/raw/buildings_data.csv
  data/raw/vehicles_data.csv
  data/scripts/get_vehicles.py
  src/components/state-details.js
Labels: front-end, data

#48 Make State Details Graph Stick On Desktop (& Fix Homepage Electrification Lines)
  package.json
  src/components/simpleareachart.js
  src/components/singlebar.js
  src/components/state-details.js
  src/styles/global.css
  src/styles/stateface/stateface.css
  yarn.lock
Labels: enhancement, front-end

#58 Add Already Electrified Summary Chart
  data/final/buildings/buildings.json
  data/final/emissions/emissions.json
  data/final/power_plants/power_plants.json
  data/final/vehicles/vehicles.json
  data/raw/buildings_data.csv
  data/scripts/get_buildings.py
  src/components/AlreadyElectrifiedChart.js
  src/components/state-details.js
Labels: enhancement, front-end

#60 Fix Mobile Styling
  gatsby-config.js
  src/components/choroplethmap.js
  src/components/simpleareachart.js
  src/components/singlebar.js
  src/pages/index.js
  src/styles/global.css
  src/styles/index.css
Labels: bug, front-end

#61 Renewable generation targets
  data/Makefile
  data/raw/state_renewable_gen_targets.csv
  data/scripts/get_target_generations.py
Labels: data
