Repository chihacknight/decarbonize-my-state, pull requests merged in 2022-05, with the labels that each got.

#69 responsive markup for power plant icons, added plant name
  data/final/buildings/buildings.json
  data/final/emissions/emissions.json
  data/final/power_plants/power_plants.json
  data/final/target_generation/target_generation.json
  data/final/vehicles/vehicles.json
  data/scripts/get_power_plants.py
  data/scripts/utils.py
  src/components/displayplants.js
  src/components/state-details.js
Labels: enhancement, front-end

#75 remove package-lock.json
  package-lock.json
Labels: bug, front-end

#74 Make State Title and Back Button Sticky
  src/components/state-details.js
  src/styles/global.css
Labels: enhancement, front-end

#76 state detail placeholder images, links & polish
  src/components/displayplants.js
  src/components/state-details.js
  src/images/car-transition.png
  src/images/coal-plant-transition.png
  src/images/electric-appliances.png
  src/images/gas-appliances.png
Labels: enhancement, front-end

#82 Make state tooltip nice and tabbable
  src/components/choroplethmap.js
  src/pages/index.js
  src/styles/global.css
Labels: bug, front-end

#86 accessibility: increase contrast on navbar and action-panel links
  src/styles/global.css
Labels: accessibility

#87 add callout to power plant map
  src/components/state-details.js
  src/images/dirty-power-plants.jpg
Labels: front-end

#98 Accessibility Fixes 2 - Fix Homepage Map Keyboard Use & Add Skip to Main Link
  src/components/AlreadyElectrifiedChart.js
  src/components/choroplethmap.js
  src/components/header.js
  src/components/state-details.js
  src/pages/404.js
  src/pages/about.js
  src/pages/index.js
  src/pages/terminology.js
  src/styles/global.css
Labels: front-end, accessibility

#107 Remove Empty Page Header Links and Add Beta Notice
  gatsby-config.js
  src/components/header.js
Labels: enhancement, front-end
