Repository chihacknight/decarbonize-my-state, pull requests merged in 2022-07, with the labels that each got.

#118 add take action links
  src/components/header.js
  src/components/state-details.js
  src/pages/index.js
  src/styles/global.css
Labels: enhancement

#123 using proper Gtag stream ID
  gatsby-config.js
Labels: bug

#122 Fix React Errors & Improve About/Take Action Styling
  src/components/state-details.js
  src/pages/about.js
  src/pages/index.js
  src/pages/take-action.js
  src/styles/global.css
Labels: bug, front-end

#125 Fix Homepage Typo
  src/pages/index.js
Labels: bug, front-end

#131 Annual Counts Fix for Vehicles & Buildings
  src/components/state-details.js
  src/pages/about.js
  src/pages/take-action.js
Labels: bug

#133 Fix Deprecated About Link and Add Car Free Note
  src/components/state-details.js
  src/pages/about.js
Labels: bug, enhancement
